# Generated by Django 5.1.1 on 2024-09-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_created_by_alter_brand_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa fa-circle', max_length=55, null=True),
        ),
    ]
