# Generated by Django 5.1.1 on 2024-09-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
