# Generated by Django 5.1.1 on 2024-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_new_price_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_Newest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_Popular',
            field=models.BooleanField(default=False),
        ),
    ]
